### ISSUE TITLE
CMS - Textedit on current page

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#1]
# Value Proposition

**As a** user
**I want to** be able to edit text nodes
**So that** the text content on the website can be modified

# Description

![Image](https://user-images.githubusercontent.com/107849620/184609419-4b954eee-7070-43e4-8af8-1852a7a89102.png)

# Acceptance Criteria

- [ ] Text nodes as clickable/selectable
- [ ] after selection, an input field appears 
- [ ] inside the input field, the user can write text
- [ ] after pressing return, the newly written text replaces the previous text nodes content

# Tasks

 - [ ] Create a new feature Branch
 - [ ] Create a Page
 - [ ] Create left side cms bar
 - [ ] Create right side iframe 
 - [ ] Create Edit Button
 - [ ] Create Save Button
 - [ ] Create/Include static website
 - [ ] Load website into iframe
 - [ ] Add Zustand 
 - [ ] Create TextNode Edit Function 
 - [ ] Add event.preventDefault() to the submit action
 - [ ] Write a test to validate the button actions

# Complexity

 L

**Comment by RobertBReich** [comment]
fixed "appears"
