### ISSUE TITLE
MovieApp: Search

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#11]
# Value Proposition

**As a** user
**I want to** be able so search for new and cool movies and tv-shows
**So that** that i can see their details 

# Description

![Image](https://user-images.githubusercontent.com/107849620/186868852-e4cd9728-d9a2-4830-981a-eb039d54b45f.png)

# Acceptance Criteria

- [ ] There should be a search input field
- [ ] When a search is entered and sent, there should be a result or an error message displayed
- [ ] results should be clickable and should bring the user to a detail page of that movie or tv-show 

# Tasks

- [ ] create a new branch
- [ ] implement a search bar
- [ ] implement the search with calls to the api
- [ ] implement the view, loading and error-handling

# Complexity

L

**Comment by UniversalTraveller** [comment]
Hi Robert,

would it make sense to split this user story? First the search and then, as a different (rather small) story, the clickability?

The user story doesn't tell me anything about how the search works. Does it just search for titles? Or for names too? Is it a fuzzy search, or does it require an exact match? Many questions.

Being nitpicky: There is a little typo, should be "sent", not "send". And some list items start with uppercase, some with lowercase - would look better if you could decide on one.
