### ISSUE TITLE
MovieApp: Language switch

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#12]
# Value Proposition

**As a** user
**I want to** have a language button switch
**So that** i can change from english to german language

# Description

![Image](https://user-images.githubusercontent.com/107849620/186903043-c66ad55b-3c50-40e0-922e-be559ef5353b.png)

# Acceptance Criteria

- [ ] There should be two buttons, one for english and german
- [ ] When one button is active, the other should go inactive
- [ ] When you click the button, the language of the entire page should change to the language selected

# Tasks

- [ ] Create new branch
- [ ] Create and insert two buttons
- [ ] Implement state management for language change (Zustand)
- [ ] Create content switches based on language state for all static text
- [ ] Rework API calls with language parameter

# Complexity

XL
