### ISSUE TITLE
MovieApp: load more content

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#13]
# Value Proposition

**As a** User
**I want to** have the ability to get more entries at the bottom of the page
**So that** I can see more content

# Description

![Image](https://user-images.githubusercontent.com/107849620/187856893-61665f91-1e72-4986-8ad2-7988fa419b26.png)

# Acceptance Criteria

- [ ] There should be a button at the bottom of the page to load more entries
- [ ] On click, there should be new content loaded

# Tasks

- [ ] Create a new branch
- [ ] Create a button
- [ ] On Click, load the next page (20 entries) into the already existing Array, keeping the old entries

# Complexity

S
