### ISSUE TITLE
MovieApp: Refactoring

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#16]
# Value Proposition

**As an** author
**I want to** refactor my code
**So that** it becomes more readable and maintainable

# Description

![Image](https://user-images.githubusercontent.com/107849620/188804327-adaa896e-795d-42d1-8e3d-afbc21adebfb.gif)

# Acceptance Criteria

- [ ] Goal is reached when it looks more pretty but still works

# Tasks

- [ ] create a new branch
- [ ] refactor all the things
- [ ] giggedy

# Complexity

M
