### ISSUE TITLE
CMS - Save Document to Server

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#2]
# Value Proposition

**As a** user
**I want to** save the edited document.
**So that** the changes I made are saved to the server.

# Description

![Image](https://user-images.githubusercontent.com/107849620/184639973-4915196b-5a9b-4909-9f92-c8db1b02691e.png)

# Acceptance Criteria

- [ ] A "save" button is displayed
- [ ] when pressed, the current document is saved

# Tasks

- [ ] create a button
- [ ] extract the modified document out of the iframe and send it to the server to be saved
- [ ] create a test to verify if the save process works properly
- [ ] create an awesome green button in Stylebook 

# Complexity

S
