### ISSUE TITLE
MovieApp: Overview Page

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#3]
# Value Proposition

**As an** user
**I want to** see an overview of recent movies and TV-Shows
**So that** I get inspired what to watch next.

# Description

![Image](https://user-images.githubusercontent.com/107849620/185147711-fa64a7c8-3b85-4d73-bb48-4fdb4ecd37b7.png)

# Acceptance Criteria

- [x] Recent Movies and/or TV-Shows should be shown with their Image
- [x] An error message should be shown if there is no internet connection or the server can't be reached

# Tasks

- [x] create a new git branch
- [x] create a basic mobile-first layout
- [x] create a header
- [x] create an Image holder Component
- [x] create a Zustand driven data Store 
- [x] create a fetch for themoviedb.org to show "recent" movies
- [x] create a Component for an error message
- [x] if response throws an error, show an error message
- [x] create the overview list from the result, using their images

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Robert,

Nice job! I have a few suggestions:

- The value proposition in most cases is written from the user perspective. In your case this is also possible, e.g.:

_As a user
I want to see an overview of recent movies and TV-Shows
so that I get inspired what to watch next._

- The scribble should only include what you have developed so far and will develop in this user story. As this is your first user story it should only include what you will develop in this user story. As far as I understand the bookmark will be part of a future user story, so it should not be visible in the scribble. Same for the pagination, unless you wanna implement it already in this user story. If so, it should be part of your acceptance criteria as well (e.g. how many movies per page, how can the user interact with your app to get to the other pages etc.).
- I would recommend to rephrase your acceptance criteria, so that you do not need to use "you", "we" ...

**Comment by ahohnsen** [comment]
And another thing: As you are working with an API, there is always the possibility that the movies might get not fetched. In case of an error you should display a message to the user. This would be also part of the acceptance criteria (and you can even add a scribble displaying the error state).
