### ISSUE TITLE
MovieApp: Bookmarks Page

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#5]
# Value Proposition

**As a** user
**I want to** bookmark new movies or tv-shows
**So that** i don't forget to watch them later

# Description

![Image](https://user-images.githubusercontent.com/107849620/185564288-a1e21b29-03ab-4cf4-bc8b-a68a9e24328a.png)

# Acceptance Criteria

- [x] The bookmark page should show all movies and tv-shows that were bookmarked
- [x] A new bookmark should be able to be set with a button on the detail page 
- [x] When clicked on the green bookmark icon of a movie inside the bookmark page, the movie should be removed from the list
- [x] Movies or TV-Shows that are bookmarked are marked with a bookmark icon 

# Tasks

- [x] create the bookmarks page
- [x] insert a bookmark button in the details page
- [x] create an Array to save the movies for the bookmarks
- [x] retrieve the information from the Array to build the list on the bookmarks page
- [x] Insert a temporary "back to the overview" button, the navigation will be inserted in a later step

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Robert,

I have a few suggestions/thoughts:

Scribble: Please fill it with realistic content and no placeholder text :) On your bookmark page only one movie image has a bookmark icon which is a bit confusing. On the bookmark page all movies/tv-shows should have a bookmark icon. On first sight I thought this would resemble the overview page 🤔 

Acceptance Criteria
- I am wondering if the little bookmark icons will be also visible on the overview page?
- What happens after clicking on the bookmark button? Will the button change color/text or is there any other visual feedback that the movie was bookmarked successfully? Can the user click again on the button to remove the movie from the bookmarks? I think that would be very handy otherwise the user would need to go to the bookmark page first to remove the movies from the bookmarks.

>  When clicked on a image of a movie inside the bookmark page, the movie should be removed from the list

- As a user I would expect that clicking on the movie would bring me to the details page of the movie. Maybe it would be a better idea to remove the movie from the list by clicking on the bookmark icon instead of the whole movie 🤔 
- As well I am wondering how the user can reach the bookmark page from the overview page or the details page. Please indicate this in your scribble and acceptance criteria 🙂

**Comment by RobertBReich** [comment]
Changed the behaviour, so the "remove bookmark" now works with the green icon. Also added a temp. back button. 

I don't get the obsession with "realistic content" on a detail page, that is only there to show where i put the bookmark button.

**Comment by j-eick** [comment]
Looks good! 👍🏼

I'm tempted to suggest, that adding the _"back to the overview" button_ to the ACs as well could be an option, but I guess you want to decide on that on the go.

**Comment by RobertBReich** [comment]
Hey Josh,
Yeah, next user story is the navigation and then the back button is obsolete.
