### ISSUE TITLE
MovieApp: Main Navigation

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#6]
# Value Proposition

**As a** user
**I want to** have a navigation at the top of the screen
**So that** i can switch between pages 

# Description

Build the main navigation so that users can get to the bookmarks from the overview or the details page 
![navigation2 excalidraw](https://user-images.githubusercontent.com/107849620/185595821-0f93492f-c419-49b5-9022-ba8d5216f1cb.png)

# Acceptance Criteria

- [x] navigation should give access to all main pages of the application

# Tasks

- [x] create the navigation in the header of the application
- [x] link all pages

# Complexity

S

**Comment by ahohnsen** [comment]
Hey Robert,

Please insert a scribble here to show off your navigation 🙂 As well, have a look at my comment under your previous user story. Even if you implement the navigation in this user story, the user should always be able to reach all pages. So in your previous user story you could implement a simple link to reach the bookmarks page.

**Comment by UniversalTraveller** [comment]
Hey Robert,

looks good. I like that this is a really small user story. A few suggestions:

- It would be nice to see the whole screen in the scribble, not just the navigation.
- Isn't there a details page too? Why doesn't it show up in the navigation?
- Maybe make it more clear to the user that the navigation items are clickable. Display them as buttons?

**Comment by RobertBReich** [comment]
Hey Andreas,

You can only get to the details page when you click on a movie. You get a movie -> movie id -> load movie details by id -> when data is there -> show details page. Without "picking" a movie, the details page would be empty.

I'll update the image. 😄

**Comment by j-eick** [comment]
Looks good. 👍🏼
