### ISSUE TITLE
MovieApp: Cast (Actors & Actresses) on Detail Page

### ISSUE THREAD

**Issue by RobertBReich** [RobertBReich/capstone-project#8]
# Value Proposition

**As a** user
**I want to** see the cast members of a movie or tv-show
**So that** i can get more information about them

# Description

![Image](https://user-images.githubusercontent.com/107849620/186162236-35d17da7-12f6-4277-8931-efee3944cb8e.png)

# Acceptance Criteria

- [ ] Cards with Cast members photo and name is shown
- [ ] When there are too many entries, the list should be scrollable sideways

# Tasks

- [ ] new git branch
- [ ] access the data from the api
- [ ] build a cast card component

# Complexity

M

**Comment by j-eick** [comment]
In case of a longer list of cast members, you should give the user a hint that the card list is scrollable. Either by partly showing the card to the very right or by some kind of indicator that signals to the user that there are more cards.
As of now I wouldn't be tempted to scroll sideways, because I don't know better.

Aside from that. Looks nice!

**Comment by RobertBReich** [comment]
done.

**Comment by j-eick** [comment]
Looks good. 🤌🏼
